# Information
site_name: 'SeAT Documentation'
site_description: 'Simple EVE Api Tool Documentation'
site_url: 'https://eveseat.github.io/docs'

# Repository
repo_name: 'eveseat/docs'
repo_url: 'https://github.com/eveseat/docs'

# Copyright
copyright: 'Copyright &copy; 2015 - 2020 Leon Jacobs'

# Documentation TOC
nav:
    - Home: index.md
    - Installation:
      - Requirements: installation/requirements.md
      - Docker Installation (4.x): installation/docker_installation.md
      - Docker Installation (5.x): installation/docker_installation_5.md
      - Manual Installation: installation/manual_installation.md
    - Upgrading:
      - General: upgrading/general.md
      - From SeAT 4.0:
          - Docker: upgrading/from_seat_4_0/docker.md
          - Bare metal: upgrading/from_seat_4_0/bare_metal.md
      - From SeAT 3.0:
        - Docker: upgrading/from_seat_3_0/docker.md
        - Bare metal: upgrading/from_seat_3_0/bare_metal.md
      - From SeAT 2.0: upgrading/from_seat_2_0.md
      - From SeAT 1.0: upgrading/from_seat_1_0.md
    - Configuration:
      - ESI Configuration: configuration/esi_configuration.md
      - Email Setup:
        - Mailgun: configuration/email_setup/mailgun.md
        - GMail: configuration/email_setup/gmail.md
      - Env File Reference: configuration/env_file_reference.md
      - EVE Administrative Contact: configuration/eve_administrative_contact.md
      - Configuration Overload: configuration/configuration_overload.md
      - SDE Overload: configuration/sde_overload.md
    - Admin Guides:
      - Admin Login: admin_guides/admin_login.md
      - Docker Admin: admin_guides/docker_admin.md
      - Authorizations: admin_guides/authorizations.md
      - Buckets: admin_guides/buckets.md
      - Squads: admin_guides/squads.md
      - Understanding Tracking: admin_guides/understanding_tracking.md
      - Scaled Deployments: admin_guides/scaled_deployments.md
    - User Guides:
      - Moons Reporter: user_guides/moons_reporter.md
    - Developer Guides:
      - Developer Installation: developer_guides/developer_installation.md
      - Job Queue Flow: developer_guides/job_queue_flow.md
      - Development Tips: developer_guides/development_tips.md
      - Notifications Implementation: developer_guides/notifications_implementation.md
      - Core Package Breakdown: developer_guides/core_package_breakdown.md
      - Package Development: developer_guides/package_development.md
      - Updating Plugins: developer_guides/updating_plugins.md
      - SeAT API: developer_guides/seat_api.md
    - Styling: styling.md
    - Community Packages: community_packages.md
    - Troubleshooting: troubleshooting.md
    - About:
      - Contact: about/contact.md
      - Reporting Bugs: about/reporting_bugs.md

# Theme Configuration
theme:
    name: 'material'
    palette:
        scheme: 'slate'
        primary: 'orange'
        accent: 'orange'
    features:
      - content.code.copy

# Customization
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - toc:
        permalink: true
extra:
  analytics:
    provider: google
    property: UA-119530306-1
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/eveseat/seat'

# Tabs customisation
extra_css:
    - css/extra_footer.css
    - css/extra_typo.css
