# Information
site_name: 'SeAT Documentation'
site_description: 'Simple EVE Api Tool Documentation'
site_url: 'https://eveseat.github.io/docs'

# Repository
repo_name: 'eveseat/docs'
repo_url: 'https://github.com/eveseat/docs'

# Copyright
copyright: 'Copyright &copy; 2015 - 2020 Leon Jacobs'

# Documentation TOC
nav:
    - Home: index.md
    - Installation:
      - Requirements: installation/requirements.md
      - Basic Installation: installation/basic_installation.md
      - Docker Installation: installation/docker_installation.md
      - Manual Installation:
        - Getting Started: installation/manual/getting_started.md
        - CentOS: installation/manual/centos.md
        - Debian: installation/manual/debian.md
        - Ubuntu: installation/manual/ubuntu.md
        - Generic: installation/manual/generic.md
      - Webservers:
        - General: installation/webservers/general.md
        - Nginx: installation/webservers/nginx.md
        - Traefik: installation/webservers/traefik.md
        - Caddy: installation/webservers/caddy.md
        - Apache: installation/webservers/apache.md
    - Upgrading:
      - General: upgrading/general.md
      - From SeAT 2.0: upgrading/from_seat_2_0.md
      - From SeAT 1.0: upgrading/from_seat_1_0.md
    - Configuration:
      - ESI Configuration: configuration/esi_configuration.md
      - Email Setup:
        - Mailgun: configuration/email_setup/mailgun.md
        - GMail: configuration/email_setup/gmail.md
      - Env File Reference: configuration/env_file_reference.md
      - EVE Administrative Contact: configuration/eve_administrative_contact.md
      - Configuration Overload: configuration/configuration_overload.md
      - SDE Overload: configuration/sde_overload.md
    - Admin Guides:
      - Docker Admin: admin_guides/docker_admin.md
      - Authorizations: admin_guides/authorizations.md
      - Squads: admin_guides/squads.md
      - Understanding Tracking: admin_guides/understanding_tracking.md
      - Scaled Deployments: admin_guides/scaled_deployments.md
    - User Guides:
      - Moons Reporter: user_guides/moons_reporter.md
    - Developer Guides:
      - Developer Installation: developer_guides/developer_installation.md
      - General Guide: developer_guides/general_guide.md
      - Job Queue Flow: developer_guides/job_queue_flow.md
      - Development Tips: developer_guides/development_tips.md
      - Core Package Breakdown: developer_guides/core_package_breakdown.md
      - Package Development: developer_guides/package_development.md
      - SeAT API: developer_guides/seat_api.md
    - Styling: styling.md
    - Community Packages: community_packages.md
    - Troubleshooting: troubleshooting.md
    - About:
      - Contact: about/contact.md
      - Reporting Bugs: about/reporting_bugs.md

# Theme Configuration
theme:
    name: 'material'
    palette:
        primary: 'grey'
        accent: 'indigo'

google_analytics:
  - 'UA-119530306-1'
  - 'auto'

# Customization
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/eveseat/seat'
# Tabs customisation
extra_css:
    - css/extra_footer.css
    - css/extra_typo.css
    - css/extra_tabs.css
extra_javascript:
    - js/extra_tabs.js
